name: Jarrett Meyer
title: Caffeine-Powered Life
email: jarrettmeyer@gmail.com
github_username: jarrettmeyer
twitter_username: jarrettmeyer

markdown: kramdown
permalink: /:year/:month/:day/:title

gems:
  - jekyll-gist

gist:
  noscript: false

kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
