name: Jarrett Meyer
title: Caffeine-Powered Life
email: jarrettmeyer@gmail.com
github_username: jarrettmeyer
twitter_username: jarrettmeyer

markdown: kramdown
permalink: /blog/:year/:month/:day/:title

kramdown:
  input: GFM
  hard_wrap: false
